### PR TITLE
Dev -> Master

### PR DESCRIPTION
**Pull request by aeksco**

### CODE REVIEW

**Comment by tans2** [comment]
So proud (y)

**Review by Dmariedwards — COMMENTED** [review]
Looks good

**Review by tans2 — APPROVED** [review]
Beautiful, outstanding, I am at a loss for words!

**Comment by JCBird1012** [comment]
In the wise words of Linus Torvalds... "As it is, the[se] patches are COMPLETE AND UTTER GARBAGE."

**Pull request merged**
